name: Windows RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  tailscale-rdp:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Tailscale (join tailnet)
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
          version: latest
          # optional: use-cache: "false"

      - name: Wait for Tailscale ready & show status
        shell: pwsh
        run: |
          Write-Output "Menunggu Tailscale siap..."
          $ready = $false
          for ($i=0; $i -lt 30; $i++) {
            try {
              $s = tailscale status --json 2>$null
              if ($s) { $ready = $true; break }
            } catch {}
            Start-Sleep -Seconds 1
          }
          if (-not $ready) {
            Write-Error "Tailscale tidak siap."
            exit 1
          }
          Write-Output "Tailscale status:"
          tailscale status
          Write-Output "Tailscale IP (IPv4):"
          tailscale ip -4

      - name: Enable RDP and create user
        shell: pwsh
        run: |
          $username = "githubRDP"
          $password = "UbahPasswordKuat123!"   # GANTI dengan password kuat sendiri
          Write-Output "Membuat/atur user: $username"
          if (-not (Get-LocalUser -Name $username -ErrorAction SilentlyContinue)) {
            net user $username $password /add
            net localgroup administrators $username /add
          } else {
            net user $username $password
          }

          Write-Output "Mengaktifkan Remote Desktop..."
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          # Cetak instruksi koneksi
          $ip = (tailscale ip -4).Trim()
          Write-Output "=== RDP READY ==="
          Write-Output "Koneksi via Tailscale IP: $ip"
          Write-Output "Gunakan alamat: $ip:3389"
          Write-Output "Username: $username"
          Write-Output "Password: (password yang ditetapkan di workflow)"
          Write-Output "================="
          
      - name: Keep runner alive (maks ~6 jam)
        shell: pwsh
        run: |
          Write-Output "Runner akan tidur supaya RDP tetap tersedia selama job berjalan..."
          Start-Sleep -Seconds 21600
